spring:
  application:
    name: socialmedia-api
  datasource:
    url: jdbc:postgresql://localhost:5432/socialmedia_db
    username: kariioke
    password: kariioke
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false